name: appalertas
description: "Proyecto de alertas en flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  flutter_local_notifications: ^17.2.1+2
  url_launcher: ^6.3.0
  sqflite: ^2.0.0+3
  dio: ^4.0.0
  telephony: ^0.2.0
  
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  firebase_messaging: ^15.0.4
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
